schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

jobs:
- job: linux
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-20.04
  steps:
    - script: './build_mobile.sh $(Build.BuildNumber) $(UPLOADCREDS)'
  displayName: 'Mobile Build'
